# Generated by Django 3.2.6 on 2022-11-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_blogmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='display_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
