# Generated by Django 3.2.6 on 2022-11-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_blogmodel_display_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='display_content',
        ),
    ]
