# Generated by Django 3.2.6 on 2022-11-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_blogmodel_display_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='summary',
            field=models.TextField(default='To read more click read more'),
        ),
    ]
