# Generated by Django 3.2.6 on 2022-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(default='info', max_length=1000),
        ),
    ]
