# Generated by Django 3.2.6 on 2022-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_blogmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(blank=True, default='info', max_length=1000),
        ),
    ]
