# Generated by Django 3.2.6 on 2022-11-22 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0009_alter_blogmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
